    - name: Prepare kernel
      run: |
        cd kernel

        mkdir -p out

        echo "== Clean source tree =="

        make mrproper


        echo "== Generate defconfig =="

        make \
          O=out \
          ARCH=arm64 \
          vendor/kona_defconfig


        echo "== Disable incompatible SCHGM =="

        scripts/config \
          --file out/.config \
          --disable CONFIG_QCOM_SCHGM || true

        scripts/config \
          --file out/.config \
          --disable CONFIG_QCOM_SCHGM_FLASH || true

        scripts/config \
          --file out/.config \
          --disable CONFIG_SCHGM_FLASH || true


        echo "== Sync config =="

        make \
          O=out \
          ARCH=arm64 \
          olddefconfig


        echo "========== SCHGM CONFIG =========="

        grep SCHGM out/.config || true